### PR TITLE
FreeBSD support

### PR DESCRIPTION
**Pull request by jbeich**
Kinda works ([package](https://www.freshports.org/x11/waybar)) but I haven't tested much.
```
$ waybar
[info] Resources files: //usr/local/etc/xdg/waybar/config, //usr/local/etc/xdg/waybar/style.css
[error] media stopped unexpectedly, is it endless?
[warning] module network: Unknown module: network
[warning] module temperature: Disabling module "temperature", Can't open /sys/class/thermal/thermal_zone0/temp
[warning] module backlight: Disabling module "backlight", No backlight found
[warning] module battery: Unknown module: battery
[warning] module battery#bat2: Unknown module: battery#bat2
[warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity
[info] Bar configured (width: 3840, height: 30) for output: DP-1
[error] mpd: Failed to connect to MPD: Connection refused
```

### CODE REVIEW

**Comment by Alexays** [comment]
A big thank for starting this, however what do you think about splitting a little more, either in different files for example because I find that it obfuscates files, for example the memory file is difficult to read

**Comment by jbeich** [comment]
> what do you think about splitting a little more

Is it good enough now? I didn't split BSD files because they share a lot of code.

**Comment by Alexays** [comment]
I'll merge this soon, is it ok for you?

**Comment by jbeich** [comment]
Sure but style maybe suboptimal. Non-FreeBSD bits were tested standalone. If there're bugs those can be fixed later as long as bisection works (i.e., avoid sqaushing on merge).

**Comment by Alexays** [comment]
Sorry for this big delay 😢
Do you think you could take another look to rebase and make sure everything's okay?

**Comment by jbeich** [comment]
Hmm, I can't figure out why TravisCI doesn't install packages on FreeBSD. It works fine in a fork.

**Comment by Alexays** [comment]
Freaking good stuff!
Just two little things, can you add `libnl` to freebsd travis deps.
And what do you think about changing the file structure for something like this:
```
└── modules/
    ├── sni/
    ├── sway/
    ├── cpu/
    |   ├── cpu.cpp
    |   ├── bsd.cpp
    |   └── linux.cpp
    ├── clock.cpp
    └── ...
```
Thanks! ❤️

**Comment by jbeich** [comment]
> can you add `libnl` to freebsd travis deps.

[netlink(7)](http://man7.org/linux/man-pages/man7/netlink.7.html) is not supported on FreeBSD, so `libnl` is not packaged.

> ```
> └── modules/
>     ├── sni/
>     ├── sway/
>     ├── cpu/
>     |   ├── cpu.cpp
>     |   ├── bsd.cpp
>     |   └── linux.cpp
>     ├── clock.cpp
>     └── ...
> ```

I've switched to cpu/common.cpp. Did you really want cpu/cpu.cpp?

**Comment by Alexays** [comment]
> netlink(7) is not supported on FreeBSD, so libnl is not packaged.

Oh yeah my bad..
> I've switched to cpu/common.cpp. Did you really want cpu/cpu.cpp?

No common.cpp is good for me!

Thanks! i'm glag to merge this PR 😄

**Pull request merged**
