### PR TITLE
Event based mediaplayer script

### PR DESCRIPTION
**Pull request by SibrenVasse**
For personal use I created an event based python script based on playerctl to use with the custom module. Currently it's specifically for Spotify.
I thought this might be useful for other users, and an improvement over the current delayWorker script.

Is this something we should work towards merging?

Current requirements:
playerctl > 2.0
python-gobject

### CODE REVIEW

**Comment by Alexays** [comment]
Nice improvement!
But why only spotify, playerctl manages other in the same way no?

**Comment by Alexays** [comment]
If you can, it would help more people ;)

**Comment by SibrenVasse** [comment]
Alright, this should work for all media players supported by playerctl.

**Comment by Alexays** [comment]
Thanks!

**Pull request merged**
