### PR TITLE
Cava module

### PR DESCRIPTION
**Pull request by LukashonakV**
Dear @Alexays , @karlstav 
This PR bring an opportunity Waybar to use [cava ](https://github.com/karlstav/cava)API in order to visualize audio right in waybar.
There are at least two methods to do such thing in Waybar:

1. Custom module
2. This PR
----
### Method 1
Advantages: relative simplicity
Disadvantages: 
1. Performance penalty (CPU/ IO) . Cava itself is working as two thread + 1 thread needs for sed + stream piping.. 
2. Prevent Waybar to show tooltips for another modules till music playing
3. cava should be run as a daemon in background. When need to restart waybar cava keeps working... so also needs to kill cava as well
### Method 2
1. cava is distributed under MIT license.. so no any issue from this point.
3. cava unfortunately does not provide all necessary API for external applications
4. I've done deep cava source code investigation... And did some code reconfiguration in order to provide necessary API from cava side. So in such case cava can be built as a separate lib.
5. Due to point 2 ... in order to have cava integrated with Waybar modified cava source should be kept in subprojects folder.
6. I used the freshest cava commits... So actually it even support pipewire server
7. I've wrote meson configuration for cava in order to be able to connect cava subproject to Waybar with meson. cava provides only autotools scripts.
8. cava config
```json
    "cava": {
//        "cava_config": "$XDG_CONFIG_HOME/cava/waybar_cava.conf",
        "framerate": 60,
        "autosens": 1,
        "sensitivity": 100,
        "bars": 14,
        "lower_cutoff_freq": 50,
        "higher_cutoff_freq": 10000,
        "method": "pulse",
        "source": "auto",
        "stereo": true,
        "reverse": false,
        "bar_delimiter": 0,
        "monstercat": false,
        "waves": false,
        "noise_reduction": 0.77,
        "format-icons" : ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█" ]
    },

```
----
Next steps:
1. I'm going to align this changes with cava's owner @karlstav 
2. If it's ok for him... I'll try to push meson cava configuration to the meson DB
3. Once both point's are done we can do rebuilding cava module and use meson wrapper. This will give us opportunity to drop cava from subprojects folder in future and use original libcava

Dear @karlstav ,
You can use subprojects/cava folder from this PR in order to:
Separate current cava into two parts:
1. libcava - it can provide all necessary API for external uses
2. cava itself can be rewritten then and use API from the libcava
3. Unfortunately I'm not familiar with autotools . But you can check meson logic(I wrote in this PR) to understand how to build cava as a lib.
4. How Waybar uses cava please check: cava.hpp and cava.cpp files in this PR:
5. main methods (API) which waybar uses now: 
- load_config
- get_input(in input/common). Provides pointer to function which (Waybar, any external application) can use to read audio source in separate thread
- audio_raw_init - initialize plan, internal C structures (like bars, bars_raw)
- cava_execute
- audio_raw_fetch - applies equalizers, monstercat, etc. functions under raw stream
Please do not hesitate and ping for any question. I'll be glad to help and have cavalib ...

https://user-images.githubusercontent.com/23121044/232246280-71d3f5cb-db11-47a4-be38-ae383ebd5e6b.mp4

### CODE REVIEW

**Comment by LukashonakV** [comment]
This is how cava looks like in waybar https://user-images.githubusercontent.com/23121044/231017123-ccd51ba6-b72d-44e5-aa4d-a63834f6d03d.mp4

**Comment by LukashonakV** [comment]
Hi @Alexays , please your opinion ? :)

**Comment by LukashonakV** [comment]
> Hi @LukashonakV, the PR LGTM, and like the method 2 except the fact that the cava source code is included in Waybar. Do you think it's possible to make a PR on cava repo to allow use of meson db? Thanks for that work!

I'm going to do that right after this PR is merged. Actually there are two issues with PR to cava:
1. This is autotools. So I'm not familiar with that and don't now how to proper build cava as a LIBCAVA with the necessary headers using autotools.
2. Even I've restructured base code and split C functionalities into necessary API cava,,,, the only cava's owner can descide wheter they good for the cava project and he can merge that

Of course I'm starting conversation with the cava project to help them to split cava into - libcava and application cava.
Once it's done I'll create PR to mesonDB to provide the right meson wrapper. 
The only thing here is a time ))) Let's see how much it will take.

**Comment by LukashonakV** [comment]
Hi @Alexays ...
It was a bit hard... 
Finally: [cava](https://github.com/karlstav/cava) owner is afraid to bring a big [PR](https://github.com/karlstav/cava/pull/496) into the master. But we agreed : I'll create a fork for that.
So... actually I created a fork which provides an opportunity to build cava as a library and in such way external applications like Waybar can use cava's API

So, please consider the freshest changes please. This time cava is not a subproject of waybar.
I've checked:
1. I built cava as a lib installed in the system and then built waybar with the installed libcava.
2. I built Waybar without installed libcava and meson used wrapper to download and compile libcava from the fork.
All cases works well.
So now looks like this PR can me merged.

Thank you

**Comment by Alexays** [comment]
Thanks a lot!
I'm good with the changes!
Pretty cool stuff :)

**Comment by Edgars-Cirulis** [comment]
Any way to not force using it ? I guess the cava.found() function dosnt work it still fails after compiling, because it requires cava dep and that what I dont like it. Make waybar less bloat.

**Comment by LukashonakV** [comment]
Hi @Edgars-Cirulis,
Please provide building logs here.. in order to have an real case we are discussing.
cava_dep is provided by the fork - libcava. So cava.found() means meson find out necessary dependency and properly uses them during waybar building.
If you want to disable cava during waybar building,n avigate to the root waybar directory and do next
```
meson configure ./build -Dcava=disabled
```
then build waybara again

**Comment by colemickens** [comment]
Can we have a ping on this thread when your changes are upstreamed? I'm going to disable cava until then.

**Comment by LukashonakV** [comment]
> Can we have a ping on this thread when your changes are upstreamed? I'm going to disable cava until then.

Hi @colemickens , according to the comments above, the upstream owner is afraid to bring massive changes in the master. Even I did all stuff to convert cava from application to the chain application + library, the cava owner suggested that I make a fork . That's the reason why wayabr uses the fork. I just brought an opportunity to have cava functionality in waybar. So you can also help me and start discussions with cavas owner @karlstav. But as far as I see, he's got a request created a long time ago.

**Pull request merged**
