### PR TITLE
mpd: add paused format string

### PR DESCRIPTION
**Pull request by cole-h**
I've been using this locally for a while and finally decided to submit this upstream, now that the MPD module doesn't segfault anymore :wink:. Let me know if there are any changes I need to make.

### CODE REVIEW

**Comment by Alexays** [comment]
Nice!
Can you also update the documentation and wiki 😄

**Comment by cole-h** [comment]
What should I say for its `default`? In its current implementation, it uses the value of `format` if nothing is specified. Does this look right?
```
*format-paused*: ++
    typeof: string ++
    default: value of *format* ++
    Information displayed when a song is paused.
```

I've got docs updated locally and will push if you think this looks good. I'll also update the wiki after we get this merged :wink:

**Comment by Alexays** [comment]
```
*format-paused*: ++
	typeof: string ++
	This format is used when a when a song is paused.
```
Something like this :)

**Comment by cole-h** [comment]
Should be good to go. It breaks away from the standard "Information shown when ___", but I don't really think that's an issue.

**Comment by Alexays** [comment]
Thanks :)
Can you update this wiki page?
https://github.com/Alexays/Waybar/wiki/Module:-MPD

**Pull request merged**
