### PR TITLE
Feature select player

### PR DESCRIPTION
**Pull request by DanielVoogsgerd**
And here is the feature itself. I verified that it work in my usecases. But yours might be different. If you don't mind testing it first that would be awesome.

This branch is based on my branch from my other PRs (#249, #250) as I needed command line arguments to implement this.

### CODE REVIEW

**Comment by Alexays** [comment]
Nice!
Do we also want to change the default config with `--player spotify`?

**Comment by DanielVoogsgerd** [comment]
I'd prefer not too. Right now, if the --player is left empty it will update the widget depending on the last player that had an event. Considering nothing is provided I think that is ideal behavior. I would suggest maybe adding ```--player spotify``` to the documentation, to showcase the functionality.

Now I'm thinking of it, it might be a good idea to change it in the example config as well, but I'll let you decide on that matter.

**Comment by Alexays** [comment]
For me, it'll better to specify `--player spotify` since it's a spotify module in the default conf

**Comment by DanielVoogsgerd** [comment]
How do you suggest implementing dynamic player recognition in that case then? I'm fine with a default but do like the dynamic possible behaviour. On top of that changing the default to ```--player spotify``` is not backwards compatible, which current behaviour is.

May I suggest we add the ```--player spotify``` to the default config. To me, it makes more sense that way.

**Comment by Alexays** [comment]
A custom module can return a json with an icon and/or a class specified, so we can specify an icon for each supported players and also a class with a background color, what do you think?

**Comment by DanielVoogsgerd** [comment]
Yeah sure, I suspect that that is more in the backend compartment. 
Do you mind finishing off that part?

**Comment by Alexays** [comment]
@DanielVoogsgerd Sure, i'll do it tomorrow ;)

**Pull request merged**
