### PR TITLE
Add image module

### LINKED ISSUE #1191: Showing an image
I am using `background-image: url("path/to/png")` to show a background image in a widget. This is especially useful, when showing plots that are updated not too frequently.

Of course this approach does not work, because the background image is set only once and is never updated. As far as I can see, GTK actually uses base64 encoded image. I wonder if this approach can somehow be fixed to work with re-rendering.

### PR DESCRIPTION
**Pull request by JakeStanger**
Resolves #1191, #944

Module which renders an image onto the bar.

Example paired with the MPD module:

image

Example config:

```json
"image/album-art": {
  "path": "/tmp/mpd_art",
  "size": 32,
  "interval": 5,
  "on-click": "mpc toggle"
}
```

A few problems:

- For some reason right click isn't working for me. All other events are.
- I don't think the image can be styled

This evening is my first dive into C++ and first dive into GTK so this probably isn't fantastic, so criticism is very welcome.

### CODE REVIEW

**Comment by bd-g** [comment]
This looks really useful - any reason we haven't merged it yet?

**Comment by bd-g** [comment]
Just kidding, there totally is a man page on this commit, I missed it.

**Comment by yemouu** [comment]
I think it would be interesting if images could be integrated with other modules like the `pulseaudio` module instead of just being it's own module so that images can be displayed depending on the state the modules and not have to wait for an interval. Would be nice for those that would rather use images over icon fonts

**Comment by Alexays** [comment]
Thanks!

**Comment by Alexays** [comment]
Can you also update the Github Wiki?

**Pull request merged**
