### PR TITLE
[DO NOT MERGE] attempt at adding on_hover_drag event (fix #866)

### LINKED ISSUE #866: [taskbar] add a on_hover_drag event
Thanks for this awesome bar + module.

The idea is you're dragging an item from a window, and want to drop it on an other window, which is either minimized or buried under windows.
after one sec hovering the destination window's item on taskbar, said window gets (un-minimized) and raised so we can drop on it.

### PR DESCRIPTION
**Pull request by Arnaudv6**
cpp junior here. I gave #866 a shot, but I am stuck [here](https://github.com/Alexays/Waybar/compare/master...Arnaudv6:master#diff-241f77e4e89b5e4a5a25eaa9dc0160ef3ec746946eecd71bf1bda58f2e3c9a3fR597)

Remove the `return` statement to try and use thread_ for a delay: this crashes.
I'd appreciate any help.

### CODE REVIEW

**Comment by Arnaudv6** [comment]
Hi there, I'd like to know if there is any plans to port waybar to gtkmm4?
As this changes dnd[1], and I want to give this MR another look.
[1] https://docs.gtk.org/gtk4/drag-and-drop.html#drop-targets

**Comment by ErikReider** [comment]
> Hi there, I'd like to know if there is any plans to port waybar to gtkmm4?

Gtk 4 doesn't support the layershell protocol

**Comment by Arnaudv6** [comment]
Thanks @ErikReider for the tip ([gtk-layer-shell/#37](https://github.com/wmww/gtk-layer-shell/issues/37))
Is there ongoing discussion on a strategy/future for Waybar, should this port never happen?

**Comment by Alexays** [comment]
Closing in favor of #1747

**Comment by Alexays** [comment]
Not same problem, sorry

**Comment by bi4k8** [comment]
I can give some guidance on implementing this if desired--sorry to have introduced merge conflicts with this!

**Comment by Arnaudv6** [comment]
@bi4k8 yes, any help welcome!

**Pull request closed without merging**
