### PR TITLE
Add style class for CPU state

### PR DESCRIPTION
**Pull request by haasn**
Fixes: https://github.com/Alexays/Waybar/issues/2911

### CODE REVIEW

**Comment by haasn** [comment]
Should be pretty straighforward, but I still need to test it; will update when I manage to get Waybar compiled

**Comment by haasn** [comment]
Appears to be working on my end.

**Comment by Alexays** [comment]
LGTM, thx

**Comment by alebastr** [comment]
Hm. [`ALabel::getState`](https://github.com/Alexays/Waybar/blob/91b79a2e9e315748f50a96603b10a960d36487ff/src/ALabel.cpp#L135) should be already doing that.

**Comment by Alexays** [comment]
fuck 🥲
you're right

**Pull request merged**
