### PR TITLE
Add info on "on-click-middle" option to custom module man page

### PR DESCRIPTION
**Pull request by fuzxi**
Fixes issue #505

### CODE REVIEW

**Comment by Alexays** [comment]
Can you also update other modules that aso implement on-click-middle :)

**Comment by fuzxi** [comment]
Updated all man pages that mention "on-click" with "on-click-middle" info

**Comment by Alexays** [comment]
Thanks a lot <3

**Comment by Alexays** [comment]
CI doesn't pass, i reverted the PR :/

**Comment by fuzxi** [comment]
Sorry, this is my first PR, so I don't know what that means. How can I fix it?

**Comment by Alexays** [comment]
There's an indention pb, you can take a look at https://travis-ci.org/Alexays/Waybar/builds/625701949

**Pull request merged**
