### PR TITLE
[hyperland/workspaces] fix: segfault on create/destroy

### PR DESCRIPTION
**Pull request by Anakael**

### CODE REVIEW

**Comment by Anakael** [comment]
@zjeffer 
Can you please test it to ensure? :)

**Comment by Alexays** [comment]
I prefer to merge it now.
Thanks!

**Comment by zjeffer** [comment]
Awesome that you found it! I can test it this evening.

**Comment by zjeffer** [comment]
I tested it out, the usual segfault is fixed, but it *very rarely* crashes here: https://github.com/Alexays/Waybar/blob/master/src/modules/hyprland/workspaces.cpp#L107. 

When it doesn't find the workspace (because it already got deleted, getting the id is impossible (workspace->get() is a nullptr) so we should just print the id we get from the function. I'll change it and test it out.

I'm testing this by scrolling incredibly rapidly through hundreds of workspaces a second, using my mouse's scrollwheel that can free scroll (Logitech G502). I don't think this happens through normal use ;)

**Comment by Anakael** [comment]
Great tests! :)

**Pull request merged**
