### PR TITLE
[sway/scratchpad] New module for scratchpad of sway

### PR DESCRIPTION
**Pull request by asas1asas200**
Scratchpad indicator for swaywm.

Related issue: #1662 .

### CODE REVIEW

**Comment by ErikReider** [comment]
Does this show each application icon just like the wlr/taskbar module or just the count?

**Comment by asas1asas200** [comment]
I only put them in the tooltip, it will show when the cursor hovered.
It shows too much information if displays all apps.
If you want to see all the scratchpad apps on the bar I can write like systray show only app icon on that, what do you think?

**Comment by ErikReider** [comment]
Yeah. An option for displaying the app icons sounds good! :)

Clicking the icons to raise the application would also be a cool addition

**Comment by Alexays** [comment]
LGTM :)

**Pull request merged**
