### PR TITLE
add JACK module

### PR DESCRIPTION
**Pull request by kennypm**
This module monitors the state of the JACK server: connection state, load percentage, buffer size, sample rate, latency, and xruns. It works with both jack2 and PipeWire, though PW users will need to build PW from git until the next release because this module depends on a fix that was just committed today.

I haven't written documentation yet but I'm happy to if the code is good to merge.

### CODE REVIEW

**Comment by Alexays** [comment]
LGTM, just the documentation.
Thx for the feature!

**Comment by kennypm** [comment]
[Wiki page](https://github.com/Alexays/Waybar/wiki/Module:-JACK)

Wasn't sure if you wanted me to add it to the sidebar yet so I didn't.

**Comment by kennypm** [comment]
@Alexays I think this should be all good to go, let me know if you need anything else from me!

**Comment by Alexays** [comment]
LGTM, yes you can add it to the sidebar :)

**Pull request merged**
