### PR TITLE
Fix twitchy scrolling on touchpads

### PR DESCRIPTION
**Pull request by Synthetica9**
Previously, any and all scroll events were interpreted as reason to switch
workspaces. This resulted in twitchy behaviour, where the scrolling was
practically unusable.

Now, we pool all scroll values, and only scroll if the value is larger than the
new config option "smooth-scrolling-threshold". If this option is not set, the
behaviour is unchanged.

### CODE REVIEW

**Comment by Synthetica9** [comment]
Also, there is inconsistency between the discrete and continuous case. In the discrete case horizontal scroll is also considered, in the continuous case this is ignored. Do we want to change this behaviour? How should this behave on "diagonal" scrolling?

**Comment by Alexays** [comment]
The actual scrolling behaviour is garbage, feel free to redo it completely :)
Also there is also a handleScroll in `ALabel.cpp` if you can also apply your changes here :)

**Comment by Synthetica9** [comment]
@Alexays Should the threshold be configurable for every individual module, or is it possible to add some global option?

**Comment by Alexays** [comment]
@Synthetica9 configurable for each module, soon I will make a kind of global configuration that the modules will inherit

**Comment by Synthetica9** [comment]
@Alexays and the diagonal case?

**Comment by Alexays** [comment]
What do you think is better?
Imo there is no need of the diagonal case.

**Comment by Synthetica9** [comment]
I see a few options:

1. Only use the principle axis,
2. Add the axes, 
3. Ignore "diagonal" scrolls, and only use events that are within a few degrees of either horizontal or vertical. 

1 and 2 seem to work pretty well. I haven't programmed 3 yet.

**Comment by Synthetica9** [comment]
(This implementation is 1. Horizontal scrolling doesn't seem to make sense for ALabel)

**Comment by Synthetica9** [comment]
@Alexays What's currently holding this up?

**Comment by Alexays** [comment]
I've been busy, i'm currently reviewing it :)

**Comment by Alexays** [comment]
Seems quite good!
Just i think it's better to rename `smooth-scrolling-threshold` to `scrolling-threshold`, right?

**Comment by Synthetica9** [comment]
> Just i think it's better to rename smooth-scrolling-threshold to scrolling-threshold, right?

Maybe? It isn't relevant to all scrolling, only to the continuous case

**Comment by Alexays** [comment]
> > Just i think it's better to rename smooth-scrolling-threshold to scrolling-threshold, right?
> 
> Maybe? It isn't relevant to all scrolling, only to the continuous case

Yeah, right, even if I think the smooth case is used in almost all cases, we'll keep `smooth-scrolling-threshold`

Thanks!

**Pull request merged**
