### PR TITLE
Add Privacy Module

### PR DESCRIPTION
**Pull request by ErikReider**
Adds a privacy module that displays a indicators if the mic is accessed, any application is playing sound, and if the screen is being shared (all through Pipewire so this won't cover XWayland screen sharing).

Each "privacy module" can be enabled/disabled individually. The PR also adds 3 custom icons to use but also allows the user to specify which XDG-icon to use.

This can be extended in the future to show Geoclue status (location usage), XWayland screen share status, and camera status :)

image
Using the default CSS

Todo:
- [x] Man Pages (remember to actually put it in the meson.build, *cough* #1566 )
- [x] Add module to README
- [x] Add default CSS
- [ ] ~Update actions with dependency changes?~
- [x] Tooltips per button

Fixes: #1776

### CODE REVIEW

**Comment by ErikReider** [comment]
The linter seems to complain about the network file (unrelated), should I push a fix here or let you fix in master? @Alexays

**Comment by ErikReider** [comment]
@Alexays should be ready for review :)

**Comment by Alexays** [comment]
LGTM!
Thanks for this nice addition :)
Can you update the Github wiki to add this new module?

**Comment by ErikReider** [comment]
> LGTM! Thanks for this nice addition :) Can you update the Github wiki to add this new module?

Done! :)

**Pull request merged**
