### PR TITLE
Add a custom formatter for "pow" numbers.

### PR DESCRIPTION
**Pull request by layus**
This PR is based on #471 just because I worked incrementally.

Instead of providing a pre-formatted string as the value for large
numbers (disk size, network bandwidth), I defined a new format that
accepts `=`, `<` and `>` as modifiers

Example:

```
format   result
>{}<     >1B<
>{:<}<   >1B     <
>{:>}<   >     1B<
>{:=}<   >1     B<

>{:>}<   > 118Mib/s<
>{:>}<   >11.8Mib/s<
>{:>}<   >1.18Mib/s<
>{:>}<   > 121kib/s<

>{:>}<   > 123Mb/s<
>{:>}<   >12.3Mb/s<
>{:>}<   >1.23Mb/s<
>{:>}<   > 123kb/s<
```

### CODE REVIEW

**Comment by Alexays** [comment]
Could you also rebase this PR, and update the wiki for the disk module on github? ❤️

**Comment by layus** [comment]
Yes, sure !

**Comment by layus** [comment]
Wiki updated :-)

**Comment by Alexays** [comment]
Thanks a lot ❤️

**Comment by layus** [comment]
@dschrempf To be honnest, the feature still has some bugs where a stray "e" sometimes appears where it should not. Rounding errors ? Some float artifact ?

> Just saw this thread and, wow, thank you! I did NOT find this in the Wiki! Maybe it could be promoted a bit more!

I would be glad to make changes. Could you tell me where you searched for that information ? It would help even more if you could make yourself a fix that matches your search.

Anyway, glad that I was useful to at least one person :-).

**Pull request merged**
