### PR TITLE
#2275  Backlight: Add minimum brightness

### PR DESCRIPTION
**Pull request by TripleTrable**
As currently it is possible to turn the brightness to zero which may not be desirable, this patch add a configurable brightness check.

### CODE REVIEW

**Comment by Alexays** [comment]
Default should still be zero to avoid breaking change

**Comment by LukashonakV** [comment]
> Default should still be zero to avoid breaking change 
In such case @TripleTrable you should assign 0.0

**Comment by TripleTrable** [comment]
I'll work on it once im back from Work

**Comment by TripleTrable** [comment]
Done. Any other requested changed?

**Comment by Alexays** [comment]
LGTM thx :)

**Pull request merged**
