### PR TITLE
Revise cava module to hide on silence

### PR DESCRIPTION
**Pull request by mutoroglin**
Hi everyone, this is a great project, thank you! It urged me to contribute....

I added to the cava module a configuration option `hide_on_silence`. If it is set to `true` the cava label is hidden if no sound is played after `sleep_timer` seconds.
If the option is not specified or set to `false` the bahaviour is unchanged (current behaviour, no hiding).

### CODE REVIEW

**Review by LukashonakV — COMMENTED** [review]
Please describe new opportunity in *cava.5.scd* man page )

**Comment by mutoroglin** [comment]
I added the explanation to the man file.

I will change the wiki as well once all discussion and review is done and you accepted the modification.

Thanks!

**Comment by Alexays** [comment]
Thanks, can you also update the GitHub wiki?

**Comment by mutoroglin** [comment]
> Thanks, can you also update the GitHub wiki?

Done!

**Pull request merged**
