### PR TITLE
dev: Added Nix Flake support

### PR DESCRIPTION
**Pull request by Narice**
- Enables Nix users to get the git version of waybar
- Enables Nix users to develop waybar easily
- Adds a fully reproducible development environment
  - The user only has to install Nix, no other depencencies
  - Automatic dev env on directory entry through .envrc

### CODE REVIEW

**Review by michaeladler — COMMENTED** [review]
Just saw this by chance. Please do not check in `.envrc` files. Either provide `.envrc.sample` or something similar or just omit the file since it's trivial.

**Comment by Alexays** [comment]
Just renamed .envrc to .envrc.sample :)

**Comment by Narice** [comment]
Thanks! Sorry, I didn't see the review before but thanks you for the merge!

**Review by mohon8156 — COMMENTED** [review]
Drims Analysis works is good.

**Pull request merged**
