### PR TITLE
Added a Hyprland backend and a Window module

### PR DESCRIPTION
**Pull request by vaxerski**
Added a backend allowing for developing hyprland's socket2 IPC-based modules, and written a simple Label for the active window title (hyprland/window)

If anything is amiss lmk.

### CODE REVIEW

**Comment by TAforever** [comment]
> 
Hello! could you please create a hyprland/language module in the future to display the keyboard layout?

**Comment by vaxerski** [comment]
Once this gets merged, sure

**Comment by NotAShelf** [comment]
I'll get to writing the man documentation shortly.

**Comment by NotAShelf** [comment]
The (initial) documentation is complete, may be subjected to change based on feedback.

- [Wiki Page](https://github.com/Alexays/Waybar/wiki/Module:-Hyprland) (Added to the sidebar as well)
- [Man Page](https://github.com/vaxerski/Waybar/blob/hyprland/man/waybar-hyprland-window.5.scd)

**Comment by vaxerski** [comment]
done

**Comment by Alexays** [comment]
Thanks <3

**Pull request merged**
