### PR TITLE
Config tweaks

### PR DESCRIPTION
**Pull request by alebastr**
Small non-functional changes to the default configuration

### CODE REVIEW

**Comment by zjeffer** [comment]
Is there a reason the default config has no extension? Adding `.jsonc` would make it slightly easier for editors to deduce the file type.

**Comment by Alexays** [comment]
Nope this can be renamed, waybar already lookup for config.jsonc

**Comment by zjeffer** [comment]
No, I meant why are we putting this file in the repo without any extension?

**Comment by alebastr** [comment]
> No, I meant why are we putting this file in the repo without any extension?

Because it was in the repo before `.jsonc` extension support. Next major release could be a good point to rename the config, both in the repo and in the installation.

For the record, that won't fix the file type detection for all editors. E.g. Emacs still needs `// -*- mode: jsonc; -*-` modeline.

**Comment by alebastr** [comment]
#2972

**Pull request merged**
