### PR TITLE
Network module rework

### LINKED ISSUE #388: Network sometimes shows as disconnected when it's not
I often get the network shown as Disconnected when it's actually not. Restarting waybar fixes it. Let me know what kind of information you need to debug this.

### PR DESCRIPTION
**Pull request by tperard**
This series of patches should fix most issue related to the network module not showing the current network state and some other issues. It should hopefully fixes #388 #494 #511.

### CODE REVIEW

**Comment by Alexays** [comment]
Hi thanks for the rework!
@pedrocr @niktob560 @tobiasjakobi @hajdamak @husam212
Can you confirm that fixes your pbs? :)

**Comment by Alexays** [comment]
LGTM, love this rework!
Can you add the disconnected state to the man?
Thanks @tperard!

**Comment by Alexays** [comment]
Will likely fix also #987 #986 #816

**Comment by tperard** [comment]
:-(, I've only try to rename the branch, I was hoping it wouldn't close the pull request.

**Comment by tperard** [comment]
I don't know if the patches would fix #987, I think that going to need testing. But if the "tun*" interface is deleted, and then another one is created, I think that would work.

For #986, that fixed by 9357a6c.

**Comment by Alexays** [comment]
Thanks!

**Comment by Alexays** [comment]
Yep @maximbaz!

**Pull request merged**
