### PR TITLE
disk: make {used} match df(1)

### PR DESCRIPTION
**Pull request by jbeich**
df's `Used` on [Linux (coreutils)](https://github.com/coreutils/coreutils/blob/aefd434e56c6e8042d98b1fee20f3e8f90a127ef/src/df.c#L936) and [FreeBSD]( https://github.com/freebsd/freebsd/blob/65faa20d1819fe7eabe79e5956c985c66cd988b6/bin/df/df.c#L533) is calculated via `f_bfree`.

### CODE REVIEW

**Comment by jbeich** [comment]
Need to confirm this actually helps.

**Comment by CedBri** [comment]
Any news on this?

**Comment by CedBri** [comment]
The patch works great on my side

**Review by Alexays — APPROVED** [review]

**Comment by chris-morgan** [comment]
I request that this please be merged. It’s a nice and simple and straightforward patch.

**Comment by Alexays** [comment]
@chris-morgan Can't merge this as the PR is marked as Draft :/

**Pull request merged**
