### PR TITLE
Image tooltip

### PR DESCRIPTION
**Pull request by Alan-Kuan**
I modified the image module to allow users setting tooltips for image modules with scripts.

Hope there's someone can help me review this.
Thanks!

### CODE REVIEW

**Comment by Alan-Kuan** [comment]
Hi @Alexays,

It's been a long while since I created this PR.
Have you taken a look? Is there anything I can help?

**Comment by Alexays** [comment]
Sorry for the delay, LGTM!
Thanks again :)

**Comment by Alexays** [comment]
Can you just update the Github wiki?

**Comment by Alan-Kuan** [comment]
> Can you just update the Github wiki?

No problem.

**Pull request merged**
