### PR TITLE
Implement windows formating in sway/workspaces

### PR DESCRIPTION
**Pull request by grimpy**
This implementation mimics to some extend the implementation of hyprland

### CODE REVIEW

**Comment by grimpy** [comment]
@Alexays anything else you want me to address in this PR?

**Comment by Alexays** [comment]
LGTM, can you also update the Github wiki?

**Comment by Alexays** [comment]
Reverted, freebsd check failed.

**Comment by alebastr** [comment]
```
../src/modules/sway/workspaces.cpp:250:20: error: no member named 'any_of' in namespace 'std::ranges'
  if (std::ranges::any_of(node["nodes"], [&](auto const &e) { return hasFlag(e, flag); })) {
      ~~~~~~~~~~~~~^
```

The CI runs FreeBSD 13.2 (still supported) with clang 14.x. It either has no `std::ranges` support or may need additional includes. Rewriting this line with `std::any_of` would be better for compatibility (and for the binary size).

**Pull request merged**
