### PR TITLE
Feature Clock: show list of time in other timezones in a tooltip

### PR DESCRIPTION
**Pull request by dartkron**
Introducing new tooltip placeholder: {timezoned_time_list}. It will be replaced with the list of times in different time zones from the config.
I've found it useful to hover the mouse pointer on time and see time in all my timezones at once. Current timezone excluding for the list, so if you will scroll over the time module and change the active timezone, this timezone will be excluded from the list and the previous active zone will be added.

How it works for me:
output

I know that this feature wasn't requested, but I found it very useful for me and hope it will be useful for someone else, who working remotely or have another kind of interest in other timezones.
Refactoring in #1277 was done as a preparation for this feature =)
Any feedback will be highly appreciated.

### CODE REVIEW

**Comment by dartkron** [comment]
Hey @Alexays! 
Sorry for bothering you, but, if you don't mind, please, give me some feedback on this PR. I just don't understand: is something wrong with it or you just haven't time to take a look.

**Comment by roland-rollo** [comment]
@Alexays is there option it would be a part of 1.0.0 release?

**Review by Alexays — APPROVED** [review]

**Comment by Alexays** [comment]
Thanks, LGTM

**Comment by Psykar** [comment]
This MR appears to have broken the FreeBSD action? Not sure if this is something that is cared about?
```
In file included from ../include/factory.hpp:5:
../include/modules/clock.hpp:39:36: error: no member named '_V2' in namespace 'std::__1::chrono'
  auto timezones_text(std::chrono::_V2::system_clock::time_point *now) -> std::string;
                      ~~~~~~~~~~~~~^
```

**Comment by dartkron** [comment]
@Psykar thank you for the update! I'll take a look in a 12 hours.

**Pull request merged**
