### PR TITLE
[sway/language] Improve sway/language

### PR DESCRIPTION
**Pull request by Anakael**
Inpired by https://github.com/Alexays/Waybar/pull/659

### CODE REVIEW

**Comment by Alexays** [comment]
Thanks!
Can you do another PR with just Dockerfiles changes?

**Comment by Anakael** [comment]
Yes, I'll do.

**Comment by eternal-sorrow** [comment]
Would be great also for this module to support `tooltip-format`

**Comment by Anakael** [comment]
@eternal-sorrow 
Ok, no problem.

**Comment by Anakael** [comment]
@eternal-sorrow 
Implemented in https://github.com/Alexays/Waybar/pull/1178

**Pull request merged**
