### PR TITLE
Update libwireplumber to >=0.4.0

### PR DESCRIPTION
**Pull request by luyu-wu**
Waybar fails to compile on the newer version of libwireplumber release (0.5.0).
Just changed the dependency.
Fixes Issue #3035

### CODE REVIEW

**Comment by andresilva** [comment]
Did you try actually building against wireplumber-0.5.0? Because it seems that there's some API changes and waybar doesn't compile.

```
../src/modules/wireplumber.cpp: In constructor 'waybar::modules::Wireplumber::Wireplumber(const std::string&, const Json::Value&)':
../src/modules/wireplumber.cpp:21:25: error: too few arguments to function 'WpCore* wp_core_new(GMainContext*, WpConf*, WpProperties*)'
   21 |   wp_core_ = wp_core_new(NULL, NULL);
      |              ~~~~~~~~~~~^~~~~~~~~~~~
In file included from /nix/store/905larf7js32s4pshc247rclshjp2103-wireplumber-0.5.0-dev/include/wireplumber-0.5/wp/wp.h:16:
/nix/store/905larf7js32s4pshc247rclshjp2103-wireplumber-0.5.0-dev/include/wireplumber-0.5/wp/core.h:45:10: note: declared here
   45 | WpCore * wp_core_new (GMainContext * context, WpConf * conf,
      |          ^~~~~~~~~~~
../src/modules/wireplumber.cpp: In member function 'void waybar::modules::Wireplumber::loadRequiredApiModules()':
../src/modules/wireplumber.cpp:259:31: error: cannot convert 'GError**' {aka '_GError**'} to 'const gchar*' {aka 'const char*'}
  259 |                               &error)) {
      |                               ^~~~~~
      |                               |
      |                               GError** {aka _GError**}
In file included from /nix/store/905larf7js32s4pshc247rclshjp2103-wireplumber-0.5.0-dev/include/wireplumber-0.5/wp/wp.h:14:
/nix/store/905larf7js32s4pshc247rclshjp2103-wireplumber-0.5.0-dev/include/wireplumber-0.5/wp/component-loader.h:45:57: note:   initializing argument 5 of 'void wp_core_load_component(WpCore*, const gchar*, const gchar*, WpSpaJson*, const g>
   45 |     const gchar * type, WpSpaJson * args, const gchar * provides,
      |                                           ~~~~~~~~~~~~~~^~~~~~~~
../src/modules/wireplumber.cpp:264:31: error: cannot convert 'GError**' {aka '_GError**'} to 'const gchar*' {aka 'const char*'}
  264 |                               &error)) {
      |                               ^~~~~~
      |                               |
      |                               GError** {aka _GError**}
```

**Comment by luyu-wu** [comment]
Huh, it built fine for me interestingly. I'll test it again now I suppose.

**Comment by khaneliman** [comment]
looks like https://github.com/Alexays/Waybar/pull/2919 was already created for this

**Comment by luyu-wu** [comment]
Ah, OK! 
My branch is building correctly, but there's still a minor issue with the wireplumber module that isn't spitting an error for some reason :)
Should we close this pull request then? I'm not to sure what's going on in the other branch, so I'm unable to contribute there.

**Pull request closed without merging**
