### PR TITLE
Calendar Year mode

### PR DESCRIPTION
**Pull request by LukashonakV**
Hi @Alexays ,
There's a huge code changing related to the new functionality. Calendar component in Clock module now supports Year view mode.

1. Clock class supports now it's own button events
2. Calendar configuration now is moved to separate group
```json
"clock": {
        "format": "{:%H:%M}  ",
        "format-alt": "{:%A, %B %d, %Y (%R)}  ",
        "tooltip-format": "<tt><small>{calendar}</small></tt>",
        "calendar": {
                    "mode"          : "year",
                    "mode-mon-col"  : 3,
                    "weeks-pos"     : "right",
                    "on-scroll"     : 1,
                    "on-click-right": "mode",
                    "format": {
                              "months":     "<span color='#ffead3'><b>{}</b></span>",
                              "days":       "<span color='#ecc6d9'><b>{}</b></span>",
                              "weeks":      "<span color='#99ffdd'><b>W{}</b></span>",
                              "weekdays":   "<span color='#ffcc66'><b>{}</b></span>",
                              "today":      "<span color='#ff6699'><b><u>{}</u></b></span>"
                              }
                    }
    },

```
3. *mode configuration* - possible values "year|month". Initial object class mode
4.  *mode-mon-col* - how many month should be printed in  row in "year" mode
5.  *on-scroll* - shifting counter (month for month mode, year for year mode)
6.  *on-click-right* | *on-click-left* - possible value now is **mode**. Switches calendar mode
7.  Supports all previous functionality

Examples
---
ps_2023-01-18-00_25_51
ps_2023-01-18-00_25_55
ps_2023-01-18-00_25_58
ps_2023-01-18-00_27_03
ps_2023-01-18-00_27_08
ps_2023-01-18-00_27_12
ps_2023-01-18-00_27_37
ps_2023-01-18-00_27_40
ps_2023-01-18-00_27_43
ps_2023-01-18-00_27_53
ps_2023-01-18-00_28_18
ps_2023-01-18-00_28_36
ps_2023-01-18-00_29_03
ps_2023-01-18-00_29_08
ps_2023-01-18-00_29_13
ps_2023-01-18-00_29_16
ps_2023-01-18-00_29_37
ps_2023-01-18-00_29_41
ps_2023-01-18-00_29_43
ps_2023-01-18-00_29_47
ps_2023-01-18-00_30_07
ps_2023-01-18-00_30_11
ps_2023-01-18-00_30_13
ps_2023-01-18-00_30_15

### CODE REVIEW

**Comment by jlaunay** [comment]
Changed my config accordingly but I cannot figure out how to display "format-alt"

**Comment by LukashonakV** [comment]
Hi @jlaunay. As it was before "format-alt": "{:%A, %B %d, %Y (%R)}  " is supported under the clock configuration. Please see my config on the top of this PR. And thanks, I really don't see description on WIKI. Will complete it soon.

**Comment by jlaunay** [comment]
Thank you for your answer. I have "format-alt" in my configuration. To be sure I copied and pasted the example in your PR but nothing to do, a left click does not change from "format" to "format-alt".

**Comment by LukashonakV** [comment]
@jlaunay can you share config please?

**Comment by jlaunay** [comment]
Here is a small recording using a minimal configuration (only the clock module centered), I tried left, right and middle click.
https://user-images.githubusercontent.com/1137028/214574774-9a31ddba-bcf1-4e76-ae82-0f9d9a025066.mp4

**Comment by LukashonakV** [comment]
@jlaunay  can you reassign mode switching to left-button please and check then format alt ? 
I mean, ```json "on-click-right": "mode", ``` change to ```json "on-click-left": "mode", ```

**Comment by jlaunay** [comment]
using
```json
"on-click-left": "mode",
```
Make left click change the mode (month/year view) but still no way to view alt format.

**Comment by LukashonakV** [comment]
Thank you. Actually just checked and see the same issue.

**Comment by jlaunay** [comment]
Glad to hear it, I was wondering what I could have done wrong again :)

**Comment by jlaunay** [comment]
Also, if it's not too difficult to add, it would be nice to have on-click-middle support for calendar as I usually use right to launch a specific calendar app and right to change format.

**Comment by LukashonakV** [comment]
@jlaunay, for now I'll fix the alt mode . I've already found the issue. For the improvements please create separate Issue. Thanks.

**Comment by LukashonakV** [comment]
@jlaunay once PR#1976 is merged, the issue will be solved.

**Comment by LukashonakV** [comment]
@jlaunay , fix was merged. Please take the freshet src and check again. Make sure - to return back switch mode
```json
"on-click-right": "mode", 
```
format-alt should work as previous on left mouse button

**Comment by apiraino** [comment]
I'm trying to use the timezone switch with the defined actions `tz_up` and `tz_down`, but I can't seem to make it work. Here a small repro:

```
{
    "layer": "top",
    "position": "bottom",
    "height": 33,
    "fixed-center": false,
    "modules-center": ["clock"],
    "clock": {
        "interval": 1,
        "format": "{:[W%W] (%a) (%Z) %Y-%m-%d - %H:%M:%S}",
        "timezones": ["", "Etc/UTC", "America/New_York", "America/Montevideo", "Asia/Tokyo"],
        "actions": {
            "on-click-right": "mode",
            "on-click-forward": "tz_up",
            "on-click-backward": "tz_down",
            "on-scroll-up": "shift_up",
            "on-scroll-down": "shift_down"
        }
    }
}
```

anything obvious I'm forgetting to configure?

thanks

**Comment by apiraino** [comment]
@LukashonakV yes, I think so. I could not yet figure out how the `tz_{up,down}` actions work. Using Waybar 0.9.20.

Let me know if you prefer me opening a separate issue.

thanks

**Comment by LukashonakV** [comment]
Hi @apiraino can you start conversation in https://github.com/Alexays/Waybar/discussions in order to have conversation is tracked.
1. Can you redefine tz_up, tz_down on another mouse buttons .. just to check there is no issue with mouse forward - backward buttons. For example just to check - `on-click-right`
2. Can you get pure example for clock module from the [wiki Example#2](https://github.com/Alexays/Waybar/wiki/Module:-Clock#example). Does it work ?

**Comment by LukashonakV** [comment]
HI @apiraino  any news ?

**Comment by apiraino** [comment]
@LukashonakV opened a [discussion ](https://github.com/Alexays/Waybar/discussions/2368)

**Pull request closed without merging**
