### PR TITLE
[hyprland/window] Implement rewrite option like in sway/window

### LINKED ISSUE #1727: Provide rewrite option for hyprland/window
Currently, the hyprland/window lacks the very useful rewrite option like what's in sway/window.

This should probably be relatively easy to add, as it should just be following the same logic.

### PR DESCRIPTION
**Pull request by herlev**
Fixes #1727

### CODE REVIEW

**Comment by herlev** [comment]
The code should probably be refactored, moving `std::string Window::rewriteTitle(const std::string& title)` to some common place and let it take the rules as an additional argument. Because right now there is code duplication between sway/window and hyprland/window.

Maybe a file somewhere in `include/util`?

**Comment by Alexays** [comment]
Yep, move this func to a common place :)
Thanks!

**Comment by herlev** [comment]
Refactoring done. I have tested it to be working on hyprland and assume it to work on sway as well since it's only a minor change.

Btw, any way to run the linter check locally before pushing?

**Comment by Alexays** [comment]
Yes you can run clang-format :)

**Comment by Alexays** [comment]
Thx!

**Pull request merged**
