### PR TITLE
Feature: created sway language submodule

### PR DESCRIPTION
**Pull request by niktob560**
This PR add a ``sway/language`` module.   
This is a clean and short-formatted display of a keyboard layout.

### CODE REVIEW

**Comment by Alexays** [comment]
Should it be named keyboard?

**Comment by niktob560** [comment]
I think that the name is not critical in this case, but if you want i'll rename it.

**Comment by Alexays** [comment]
Can you update the man and the github wiki?
Once done i'll merge the PR, thanks!

**Comment by niktob560** [comment]
Just done with the man and the github wiki
Can you, please, assign ``hacktoberfest-accepted`` label to the PR?

**Comment by Alexays** [comment]
Sure done, thanks for your work!

**Pull request merged**
