### PR TITLE
Add timezone config to clock module

### PR DESCRIPTION
**Pull request by spk**
Hi, not sure its a clean way to do that but it work and fallback to the OS TZ when timezone is invalid, wdyt ?
ref https://github.com/Alexays/Waybar/issues/223

### CODE REVIEW

**Comment by Alexays** [comment]
Thanks! But that's not compatible with multiple clock modules :/
Maybe we can give a shot to https://howardhinnant.github.io/date/tz.html

**Comment by spk** [comment]
I'm having issue using the lib with just [this](https://github.com/Alexays/Waybar/pull/285/commits/0af3c2260b24fef44c5542fcddd36290d726ae86) I'm having this error on ninja build:

```
/usr/bin/ld: waybar@exe/src_modules_clock.cpp.o: in function `waybar::modules::Clock::update()':
clock.cpp:(.text+0x84): undefined reference to `date::locate_zone(std::basic_string_view<char, std::char_traits<char> >)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

I will need some help @Alexays if you can, I'm not a cpp expert and maybe I did some misconfiguration with the meson build system that is new to me, thanks

**Comment by Alexays** [comment]
@spk Just tested and seems a pb with the wrap file :/
I'll test something

**Comment by spk** [comment]
Look like related with this issue https://github.com/HowardHinnant/date/issues/398 tried to set `HAS_STRING_VIEW=0` on the meson.build of the subproject but had same issue ¯\_(ツ)_/¯

**Comment by nerddan** [comment]
> Thanks! But that's not compatible with multiple clock modules :/
> Maybe we can give a shot to https://howardhinnant.github.io/date/tz.html

Having multiple clock modules with different tz is impossible? That's quite a shame!

**Comment by Alexays** [comment]
Done in #560

**Pull request closed without merging**
