### PR TITLE
Allow scrolling on the entire bar surface

### PR DESCRIPTION
**Pull request by RX14**
It's ugly, but it works.

Closes https://github.com/Alexays/Waybar/issues/225

### CODE REVIEW

**Comment by Alexays** [comment]
Thansk!
Oh I didn't understand it like that, I'm going to push on this pr to make the code cleaner :)

**Comment by RX14** [comment]
Thanks! This code is definitely a lot cleaner.

However, the name "disable-workspace-scroll" doesn't make 100% sense with the new location in the config. It should probably be called `"disable-bar-scroll"` now.

**Comment by Alexays** [comment]
Sure you can make a PR and update the wiki if you have time :)

**Comment by RX14** [comment]
Done in https://github.com/Alexays/Waybar/pull/326

**Comment by RX14** [comment]
So, this is supposed to *not* scroll the workspaces when you scroll on a widget with a scroll handler set, for example the pulseaudio widget. 

However, somehow the scroll event gets delivered to the window scroll event handler *first*, *then* the event handler for the widget?? Which, from reading the gtk event handling docs, makes absolutely no sense. And doing some `gdb` debugging, it seems there are two different events?

I'm confused by this, and I'd like to fix this so that widgets with scroll handlers eat the scroll events and do not scroll workspaces, but I don't have time to debug further.

**Pull request merged**
