### PR TITLE
feat(battery): added support for battery state-based classes on the entire waybar

### PR DESCRIPTION
**Pull request by ArneshRC**
The battery module now applies a single battery state-based class, `.battery-<state>` on the entire waybar.

This could be useful for, say, changing the bar's background color based on battery level.

**config.jsonc:**

```json
"battery": {
    "states": {
        "warning": 30,
        "critical": 15
    },
}
```

**style.css:**

```css
window#waybar.battery-warning {
  background-color: rgba(247, 218, 68, 0.2);
}

window#waybar.battery-critical {
  background-color: rgba(247, 68, 68, 0.2);
}
```

I'm sure there are quite a few users who would appreciate this feature: https://www.reddit.com/r/swaywm/comments/kuf9sm/make_waybar_turn_red_as_warning/

### CODE REVIEW

**Comment by Alexays** [comment]
LGTM, can you update the man and github wiki to show this new feature? :)

**Comment by ArneshRC** [comment]
Done! :)

**Comment by ArneshRC** [comment]
Made some small changes. As of [d14a4a2](https://github.com/Alexays/Waybar/pull/2810/commits/d14a4a2b1aa6b4a9af15b345f1435e68103c5d26), everything's working as expected.

**Comment by Alexays** [comment]
Thanks!

**Pull request merged**
