### PR TITLE
Added light module (brightness)

### PR DESCRIPTION
**Pull request by AlessioDP**
Reference to #177 

I have added a new module called 'light', this supports [light](https://github.com/haikarainen/light) brightness tool.

Features of light module:
- [x] Build option to enable light module
- [x] Show/increase/decrease brightness
- [x] Scroll support
- [x] `scroll-step` to choose brightness change
- [x] Update brightness value on scroll
- [x] Styling
- [ ] Upper and lower brightness limits
- [ ] Format icons
- [ ] On click events
- [ ] Wiki page

<br>

Further improvements:
- Now modules inside `config` are in alphabetic order (except for sway and customs), like `style.css`
- Changed cpu style color to `black` instead of `#000000`

### CODE REVIEW

**Comment by SethBarberee** [comment]
Would it be beneficial to allow the user to redefine the backlight commands? Mainly wondering if it would be possible to use other tools besides `light`.

**Comment by AlessioDP** [comment]
Lets see what thinks @Alexays about that :)

It will be quite similar to a custom module but this will allow you to set a limit for brightness and is strictly related on how to increase/decrease brightness.

**Comment by Alexays** [comment]
This module is pretty similar to a custom module, otherwise the #181 implementation is more lower level compared to this one, so lower memory footprint and lower cpu impact.

**Comment by AlessioDP** [comment]
That implementations works on my system so I am okay with that, but missing some features like scroll to change brightness and the code is quite different from yours.

**Comment by ianhattendorf** [comment]
I like the scrolling! I've been thinking about a way to update brightness as a 2nd pass for my module, it's easy enough to do through `udev` via `udev_device_set_sysattr_value` but I wasn't sure about the UX. I went down this path to try and keep the dependencies and resource usage to a minimum and avoid shelling out to another process.

@AlessioDP would you be interested in merging your scroll functionality into mine? I can also give it a shot as I was already planning on looking into it later tonight or tomorrow when I get the time.

**Comment by AlessioDP** [comment]
Sure, I will.
I'm working on merge it into custom module too ;)

Just I'm not familiar with C++ and I am strictly following the structure that @Alexays used, yours is a little bit different so I need some time to do it :P

**Comment by Alexays** [comment]
Thanks anyway @AlessioDP :smiley:

**Pull request closed without merging**
