### PR TITLE
Persistent workspaces for [wlr/workspaces]

### LINKED ISSUE #1629: [wlr/workspaces] Feature request: Persistent workspaces
Currently, there is no option to have persistent workspaces on wlr/workspaces, only showing workspaces that have window or windows in them.
This just hurts ricing and usability on anything other than sway.
I have not found an answer as to why this isn't possible.

### PR DESCRIPTION
**Pull request by MonstrousOgre**
Closes #1629, where multiple users have confirmed it's working

Config works identical to persistent workspaces in [sway/workspaces]

It had issues when used with the "all-outputs" option. I've made it so the two options can't be used together.

### CODE REVIEW

**Comment by Spaxly** [comment]
@Alexays

**Comment by Macic-Dev** [comment]
Great work, I hope this gets merged soon!

**Comment by Alexays** [comment]
LGTM, thx!

**Comment by MonstrousOgre** [comment]
@Alexays I edited the wiki to include instructions for it.

**Pull request merged**
